directories:
  output: release
  buildResources: build
appId: com.hospital.or-scheduling
productName: Operationssals Personalschema
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
win:
  target:
    - target: portable
      arch:
        - x64
portable:
  artifactName: OR-Scheduling-Portable.exe
electronVersion: 36.3.2
